routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BlogController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('blog');
});

Route::resource('blog', BlogController::class);

app/Models/Blog.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title','short_description','description'
    ];

    /***
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    // get all tags related to the blog
    public function allTags()
    {
        return $this->hasMany(BlogTags::class, 'blog_id');
    }
}

app/Models/BlogTags.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class BlogTags extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'blog_id','tags'
    ];
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use App\Models\Blog;
use App\Models\BlogTags;
use Illuminate\Http\Request;
use Exception;

class BlogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        try {
            $blogs = Blog::with('allTags')->latest()->get();
            return view('blog.list', compact('blogs'));
        } catch (Exception $e) {
            return redirect()->back()->with(['status' => 'danger','message' => $e->getMessage()])->withInput();
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $allTags = $this->getAllTags();
        return view('blog.form', compact('allTags'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            $validatedData = $this->validate(
                $request,
                [
                    'title' => 'required|min:5|max:30',
                    'short_description' => 'required|min:10|max:80',
                    'description' => 'required',
                    'tags' => 'required',
                    'tags.*' => 'required'
                ]
            );

            $blog = Blog::create(
                [
                'title' => $request->title,
                'short_description' => $request->short_description,
                'description' => $request->description,
                ]
            );

            if ($request->tags) {
                $this->storeTags($request->tags, $blog->id);
            }

            return redirect()
                ->route('blog.index')
                ->with(['status' => 'success','message'=>'Blog created successfully !!']);
        } catch (Exception $e) {
            return redirect()->back()->with(['status' => 'danger','message' => $e->getMessage()])->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Blog $blog
     * @return \Illuminate\Http\Response
     */
    public function show(Blog $blog)
    {
        try {
            $blog = Blog::with('allTags')->where('id', $blog->id)->first();
            return view('blog.view', compact('blog'));
        } catch (Exception $e) {
            return redirect()->back()->with(['status' => 'danger','message' => $e->getMessage()])->withInput();
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Blog $blog
     * @return \Illuminate\Http\Response
     */
    public function edit(Blog $blog)
    {
        try {
            $blog = Blog::with('allTags')->where('id', $blog->id)->first();
            if ($blog->allTags->toArray()) {
                $blog->selectedTags = $blog->allTags->pluck('tags')->toArray();
            }
            $allTags = $this->getAllTags();
            return view('blog.form', compact('blog', 'allTags'));
        } catch (Exception $e) {
            return redirect()->back()->with(['status' => 'danger','message' => $e->getMessage()])->withInput();
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Models\Blog         $blog
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Blog $blog)
    {
        try {
            $validatedData = $this->validate(
                $request,
                [
                    'title' => 'required|min:5|max:30',
                    'short_description' => 'required|min:10|max:80',
                    'description' => 'required',
                    'tags' => 'required',
                    'tags.*' => 'required'
                ]
            );

            // update blog data
            Blog::where('id', $blog->id)->update(
                [
                'title' => $request->title,
                'short_description' => $request->short_description,
                'description' => $request->description,
                ]
            );
            // update blog data

            // store blog tags data
            if ($request->tags) {
                $this->storeTags($request->tags, $blog->id);
            }

            return redirect()
                ->route('blog.show', [$blog->id])
                ->with(['status' => 'success','message'=>'Blog updated successfully !!']);
        } catch (Exception $e) {
            return redirect()->back()->with(['status' => 'danger','message' => $e->getMessage()])->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Blog $blog
     * @return \Illuminate\Http\Response
     */
    public function destroy(Blog $blog)
    {
        try {
            $blog->delete();
            return redirect()
                ->route('blog.index')
                ->with(['status' => 'success','message'=>'Blog Removed successfully !!']);
        } catch (Exception $e) {
            return redirect()->back()->with(['status' => 'danger','message' => $e->getMessage()])->withInput();
        }
    }

    /**
     * Get resources of the blog related tags.
     *
     * @return \Illuminate\Http\Response
     */
    public function getAllTags()
    {
        return BlogTags::select('tags')->groupBy('tags')->get();
    }

    /**
     * Remove the resources of the current blog and attach updated tags.
     *
     * @param \App\Models\BlogTags $tagData
     * @param \App\Models\Blog     $blogID
     */
    public function storeTags($tagData, $blogID)
    {
        BlogTags::where('blog_id', $blogID)->delete();
        foreach ($tagData as $tags) {
            BlogTags::create(
                [
                'blog_id' => $blogID,
                'tags' => $tags,
                ]
            );
        }
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/blog/form.blade.php
@extends('layouts.app')
@section('title') {{'Save Blog'}} @endsection
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ __('Save Blog') }} <a href="{{route('blog.index')}}" class="btn btn-primary float-right">Back to Blog List</a></div>                

                <div class="card-body">

                    <form method="POST" action="{{ isset($blog) ? route('blog.update',$blog->id) : route('blog.store')}}" id="blog-form">
                    @if(isset($blog))
                    {{ method_field('PATCH') }}
                    @endif
                    @csrf      

                        <div class="form-group row">
                            <label for="name" class="col-md-2 col-form-label text-md-right">{{ __('Title') }}*</label>
                            <div class="col-md-8">
                                <input id="title" type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ isset($blog->title) ? $blog->title : old('title') }}" required autofocus placeholder="Blog Title">
                                @error('title')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="short_description" class="col-md-2 col-form-label text-md-right">{{ __('Short Description') }}*</label>
                            <div class="col-md-8">
                                <textarea id="short_description" class="form-control @error('short_description') is-invalid @enderror" name="short_description" required autofocus rows="6" placeholder="Blog Short Description">{{ isset($blog->short_description) ? $blog->short_description : old('short_description') }}</textarea>
                                @error('short_description')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>   

                        <div class="form-group row">
                            <label for="description" class="col-md-2 col-form-label text-md-right">{{ __('Description') }}*</label>
                            <div class="col-md-8">
                                <textarea id="description" class="form-control @error('description') is-invalid @enderror" name="description" required autofocus rows="6" placeholder="Blog Description">{{ isset($blog->description) ? $blog->description : old('description') }}</textarea>
                                @error('description')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>  

                        <div class="form-group row">
                            <label for="tags" class="col-md-2 col-form-label text-md-right">{{ __('Tags') }}*</label>
                            <div class="col-md-8">
                                <select class="form-control @error('tags') is-invalid @enderror" multiple="multiple" name="tags[]" id="tags">                                    
                                    @forelse($allTags as $tag)                                        
                                        <option value="{{$tag->tags}}" @if(!empty($blog->selectedTags)) @if(in_array($tag->tags,$blog->selectedTags)) selected @endif  @endif>{{$tag->tags}}</option>
                                    @empty
                                    <option>New Blog</option>
                                    <option>Technology</option>                                
                                    @endforelse      
                                </select>                                                                
                            </div>                            
                        </div>  

                        <div class="form-group row mb-0">
                            <div class="col-md-8 offset-md-2">
                                <button type="submit" class="btn btn-success"">
                                    {{ __('Save Blog') }}
                                </button>
                                <a href="{{route('blog.index')}}" class="btn btn-danger">Back to List</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('js_script')
<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.0/jquery.min.js'></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.min.js'></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.full.min.js'></script>

<script type="text/javascript">
$(document).ready(function() {
    $('#tags').select2({
     tags: true
    });

    $("#blog-form").validate({
        rules: {
            title: {
                required: true,
                minlength:5,
                maxlength:30
            },
            short_description: {
                required: true,
                minlength:10,
                maxlength:80
            },
            description: {
                required: true,
                minlength:5,
            },
            'tags[]': {
               required: true,
           }
       },
       messages : {
        title: {
            required: "Title is required",    
            minlength: "Title must be at least 5 characters long",
            maxlength: "Maximum 30 characters allowed",
        },
        short_description: {
            required: "Short description is required",      
            minlength: "Short description must be at least 10 characters long",
            maxlength: "Maximum 80 characters allowed",
        },
        description: {
            required: "Description is required",      
            minlength: "Description must be at least 5 characters long",            
        },
    }});
});
</script>
@endpush

@push('css_list')
<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css'>
<style>
#tags {
  width: 100%;
}
</style>
@endpush

resources/views/blog/list.blade.php
@extends('layouts.app')
@section('title') {{'Blog List'}} @endsection
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">

            @if (session('status'))
            <div class="alert alert-{{session('status')}}" role="alert">
                {{ session('message') }}
            </div>
            @endif                            

            <div class="card-columns row m-10">
                @forelse($blogs as $key => $blog)
                <div class="card @if($key+1 === 1) col-md-12 @endif" style="width: 18rem;">
                    <div class="card-body">                        
                        <h5 class="card-title @if($key+1 === 1) first_blog @endif">{{$blog->title}}</h5>                        
                        <h6 class="card-subtitle mb-2 text-muted"><i class="fa fa-clock-o" title="Publish Date"></i> {{$blog->created_at->diffForHumans()}}</h6>
                        <hr/>
                        <p class="card-text">{!! htmlentities(substr(strip_tags(trim(preg_replace('/<[^>]*>/', ' ',@$blog->short_description))),  0, 20),ENT_QUOTES | ENT_IGNORE, "UTF-8") !!}</p></p>
                        
                        @if (count($blog->allTags) > 0)
                            <p><strong>Tags:</strong>
                                @foreach($blog->allTags as $TagKey => $tagData)
                                    <span class="badge badge-success">{{ $tagData->tags }}</span>
                                @endforeach
                            </p>
                        @endif
                    </div>
                    <div class="card-footer bg-transparent border-success">
                        <a href="{{route('blog.show',$blog->id)}}" class="card-link">
                            <i class="fa fa-eye" title="update blog detail page"></i> View Blog            
                        </a>
                    </div>
                </div>         
                @empty
                    <h3 class="text-center">No Blog Found !!</h3>                    
                @endforelse
            <div>
        </div>
    </div>
</div>
@endsection
@push('css_list')
<style>
    .first_blog {
        font-size: 22px;
    }
    .card-columns {
        margin: 30px;
    }
</style>
@endpush

resources/views/blog/view.blade.php
@extends('layouts.app')
@section('title') {{$blog->title}} @endsection
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
             @if (session('status'))
                <div class="alert alert-{{session('status')}}" role="alert">
                    {{ session('message') }}
                </div>
            @endif                            

            <div class="card margin_area">
                <div class="card-header"><strong>Blog Detail</strong>
                <a href="{{route('blog.index')}}" class="btn btn-primary float-right margin_area">Back to Blog List</a>
                <a href="{{route('blog.edit',$blog->id)}}" class="float-right btn btn-primary margin_area">
                    <i class="fa fa-pencil" title="update blog detail page"></i> Update Blog          
                </a>
            </div>

                <div class="card-body">
                    <div class="form-group row">
                        <label for="name" class="col-md-2 text-md-right"><strong>{{ __('Title') }}:</strong></label>
                        <div class="col-md-8">
                            {{$blog->title}}
                        </div>

                    <form action="{{ route('blog.destroy', $blog->id)}}" method="POST" onsubmit="return confirm('Do you really want to remove this blog?');">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-sm btn-danger"><i class="fa fa-remove"></i>&nbsp;Remove Blog</button>
                        </form>
                    </div>

                    <div class="form-group row">
                        <label for="name" class="col-md-2 text-md-right"><strong>{{ __('Short Description') }}:</strong></label>
                        <div class="col-md-8">
                            {{$blog->short_description}}
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="name" class="col-md-2 text-md-right"><strong>{{ __('Description') }}:</strong></label>
                        <div class="col-md-8">
                            {{$blog->description}}
                        </div>
                    </div>

                    @if($blog->allTags->toArray())
                    <div class="form-group row">
                        <label for="name" class="col-md-2 text-md-right"><strong>{{ __('Tags') }}:</strong></label>
                        <div class="col-md-8">
                            @foreach($blog->allTags as $TagKey => $tagData)
                                <span class="badge badge-success">{{ $tagData->tags }}</span>
                            @endforeach
                        </div>
                    </div>
                    @endif

                    @if($blog->created_at)
                    <div class="form-group row">
                        <label for="name" class="col-md-2 text-md-right"><strong>{{ __('Publish Date') }}:</strong></label>
                        <div class="col-md-8">
                            {{$blog->created_at->diffForHumans()}}
                        </div>
                    </div>
                    @endif

                    @if($blog->updated_at)
                    <div class="form-group row">
                        <label for="name" class="col-md-2 text-md-right"><strong>{{ __('Last Updated Date') }}:</strong></label>
                        <div class="col-md-8">
                            {{$blog->updated_at->diffForHumans()}}
                        </div>
                    </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@push('css_list')
<style>
.margin_area{
    margin: 5px;
}
</style>
@endpush

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@yield('title')- {{ config('app.name', 'Blog Management') }}</title>
    <link rel="shortcut icon" href="{{ asset('favicon.png') }}" />    
    <!-- Scripts -->
    
    <!-- <script src="{{ asset('js/app.js') }}" defer></script> -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    @stack('css_list')
    @stack('js_script')

</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/blog') }}">
                    {{ config('app.name', 'Blog Management') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>                

                <div class="collapse navbar-collapse" id="navbarSupportedContent">                    
                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">                        
                        <li class="nav-item dropdown">                            
                            <a class="btn btn-success" href="{{ route('blog.create') }}">
                            {{ __('Add New Entry') }}
                        </a>
                    </li>                    
                </ul>
            </div>
        </div>
    </nav>
    <main class="py-4">
        @yield('content')
    </main>
</div>
</body>
</html>